config/routes.rb
Fastscrum::Application.routes.draw do

  resources :projects do
    match "/histories_current" => "projects#histories_current", via: [:get]
    resources :histories do
      match "/move_to" => "histories#move_to", via: [:get]
      resources :tasks
    end
  end

  get "home/index"

  root to: "home#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :history
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_history

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @history.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_history_path(@project, @history), notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Set the current history
    def set_history
      @project = Project.find(params[:project_id])
      @history = History.find(params[:history_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :comments, :history_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for(@task, url: project_history_tasks_path(@project, @history), html: {class: "form-horizontal"} ) do |f|
  .col-lg-6
    .well
      - if @task.errors.any?
        .alert.alert-danger
          %h2
            = pluralize(@task.errors.count, "error")
            prohibited this task from being saved:
          %ul
            - @task.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        %legend Create new history for this project
        .form-group
          = f.label :name, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_field :name, class: "form-control"
        .form-group
          = f.label :description, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :description, class: "form-control"
        .form-group
          = f.label :comments, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :comments, class: "form-control"
        .form-group
          .col-lg-10.col-lg-offset-2
            = f.submit "Save changes", class: "btn btn-danger"
            or
            = link_to 'Back', project_history_path(@project, @history), class: 'btn btn-default'

app/views/tasks/edit.html.haml
%h1 Editing task
= render 'form'
= link_to 'Show', @task
|
\#{link_to 'Back', tasks_path}

app/views/tasks/index.html.haml
%h1 Listing tasks
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Comments
      %th History
      %th
      %th
      %th
  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.comments
        %td= task.history_id
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
.page-header
  %h2 New task

= render 'form'