config/routes.rb
Fastscrum::Application.routes.draw do

  resources :projects do
    match "/histories_current" => "projects#histories_current", via: [:get]
    resources :histories do
      match "/move_to" => "histories#move_to", via: [:get]
      resources :tasks
    end
  end

  get "home/index"

  root to: "home#index"

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :project
  has_many :tasks, dependent: :destroy

end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    @tasks = @history.tasks
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = @project.histories.build(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to project_path(@project), notice: 'History was successfully created.' }
        format.json { render action: 'show', status: :created, location: @history }
      else
        format.html { render action: 'new' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /history/1/move_to
  def move_to
    @history = History.find params[:history_id]
    respond_to do |format|
      if @history.update_attributes(state: params[:phase])
        format.html { redirect_to :back, notice: 'History was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to project_histories_url(@project) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:name, :puntuation, :finished_definition, :comments, :project_id)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.haml
= form_for(@history, url: project_histories_path, html: {class: "form-horizontal"} ) do |f|
  .col-lg-6
    .well
      - if @history.errors.any?
        .alert.alert-danger
          %h2
            = pluralize(@history.errors.count, "error")
            prohibited this history from being saved:
          %ul
            - @history.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        %legend Create new history for this project
        .form-group
          = f.label :name, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_field :name, class: "form-control"
        .form-group
          = f.label :puntuation, class: "col-lg-2 control-label"
          .col-lg-10
            = f.number_field :puntuation, class: "form-control"
        .form-group
          = f.label :finished_definition, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :finished_definition, class: "form-control"
        .form-group
          = f.label :comments, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :comments, class: "form-control"
        .form-group
          .col-lg-10.col-lg-offset-2
            = f.submit "Save changes", class: 'btn btn-danger'
            or
            = link_to 'Back', project_path(@project), class: 'btn btn-primary'
  .col-lg-6
    = image_tag "card.png", style: "margin-top: -50px;"

app/views/histories/edit.html.haml
%h1 Editing history
= render 'form'
= link_to 'Show', @history
|
\#{link_to 'Back', histories_path}

app/views/histories/index.html.haml
.page-header
  %h2 Listing histories

%table.table
  %thead
    %tr
      %th Name
      %th Puntuation
      %th Finished definition
      %th Comments
      %th
      %th
      %th
  %tbody
    - @histories.each do |history|
      %tr
        %td= history.name
        %td= history.puntuation
        %td= history.finished_definition
        %td= history.comments
        %td= link_to 'Show', project_history_path(@project, history), class: 'btn btn-info'
        %td= link_to 'Edit', edit_project_history_path(@project, history), class: 'btn btn-warning'
        %td= link_to 'Destroy', project_history_path(@project, history), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
%br/
= link_to "See related project", project_path(@project), class: 'btn btn-lg btn-info'
or create
= link_to 'New History', new_project_history_path(@project), class: 'btn btn-lg btn-primary'

app/views/histories/new.html.haml
.page-header
  %h2
    New history
    %small
      for: {
      = @project.name
      }

= render 'form'

app/views/histories/show.html.haml
.page-header
  %h2= @history.name
  %p
    %strong Puntuation:
    = @history.puntuation
  %p
    %strong Finished definition:
    = @history.finished_definition
  %p
    %strong Comments:
    = @history.comments
  %br
  = link_to 'Edit', edit_project_history_path(@project, @history), class: 'btn btn-warning'
  |
  \#{link_to 'Back', project_path(@project), class: 'btn btn-default' }
  |
  = link_to "Add new task", new_project_history_task_path(@project, @history), class: 'btn btn-danger'

- if notice
  .alert.alert-info
    %p#notice= notice

.page-header
  %h4 Related Tasks:
  .row
    .col-lg-8
      %b
        = @tasks.count
        related tasks
    .col-lg-4
      %input{type: "search", class: "form-control", placeholder: "Find on tasks" }

.row
  .col-lg-6
    %center
      %p
        %b Tasks
    - @tasks.each do |t|
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            Name:
            = t.name
        .panel-body
          %p
            %b Description
            = t.description
          %p
            %b Comments:
            = t.comments