config/routes.rb
Fastscrum::Application.routes.draw do

  resources :projects do
    match "/histories_current" => "projects#histories_current", via: [:get]
    resources :histories do
      match "/move_to" => "histories#move_to", via: [:get]
      resources :tasks
    end
  end

  get "home/index"

  root to: "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name
  has_many :histories, dependent: :destroy

  # attachments
  # Avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Reference document
  has_attached_file :reference_document, :default_url => "/images/:style/missing.doc"

  # Specification document
  has_attached_file :specification_document, :default_url => "/images/:style/missing.doc"


  # Getting histories from this project
  def histories_pending
    histories.where(state: "pending")
  end

  def histories_current
    histories.where(state: "current")
  end

  def histories_finished
    histories.where(state: "finished")
  end

  def histories_canceled
    histories.where(state: "canceled")
  end

  def histories_testing
    histories.where(state: "testing")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/1/current
  # List the history with state = current on this project
  def histories_current
    @project = Project.find(params[:project_id])
    @histories = @project.histories_current
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :mision, :vision, :description, :reference_document, :comments, :specification_document, :avatar, :tecnical_document)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_file.html.haml
.col-lg-6
  .well
    %form.form-horizontal
      %fieldset
        %legend Legend
        .form-group
          %label.col-lg-2.control-label{:for => "inputEmail"} Email
          .col-lg-10
            %input#inputEmail.form-control{:placeholder => "Email", :type => "text"}/
        .form-group
          %label.col-lg-2.control-label{:for => "inputPassword"} Password
          .col-lg-10
            %input#inputPassword.form-control{:placeholder => "Password", :type => "password"}/
            .checkbox
              %label
                %input{:type => "checkbox"}/
                Checkbox
        .form-group
          %label.col-lg-2.control-label{:for => "textArea"} Textarea
          .col-lg-10
            %textarea#textArea.form-control{:rows => "3"}
            %span.help-block A longer block of help text that breaks onto a new line and may extend beyond one line.
        .form-group
          %label.col-lg-2.control-label Radios
          .col-lg-10
            .radio
              %label
                %input#optionsRadios1{:checked => "checked", :name => "optionsRadios", :type => "radio", :value => "option1"}/
                Option one is this
            .radio
              %label
                %input#optionsRadios2{:name => "optionsRadios", :type => "radio", :value => "option2"}/
                Option two can be something else
        .form-group
          %label.col-lg-2.control-label{:for => "select"} Selects
          .col-lg-10
            %select#select.form-control
              %option{:selected => "selected"} 1
              %option 2
              %option 3
              %option 4
              %option 5
            %br/
            %select.form-control{:multiple => "multiple"}
              %option 1
              %option 2
              %option 3
              %option 4
              %option 5
        .form-group
          .col-lg-10.col-lg-offset-2
            %button.btn.btn-default Cancel
            %button.btn.btn-primary{:type => "submit"} Submit

app/views/projects/_form.html.haml
= form_for(@project, html: {class: "form-horizontal", multipart: true}) do |f|
  .col-lg-6
    .well
      - if @project.errors.any?
        .alert.alert-danger
          %h2
            = pluralize(@project.errors.count, "error")
            prohibited this project from being saved:
          %ul
            - @project.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        %legend Create a new project for manage
        .form-group
          = f.label :name, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_field :name, class: "form-control"
        .form-group
          = f.label :mision, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :mision, class: "form-control", rows: "3"
        .form-group
          = f.label :vision, class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :vision, class: "form-control", rows: "2"
        .form-group
          = f.label :description, class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :description, class: "form-control", rows: "3"
  .col-lg-6
    .well
      %fieldset
        %legend More documentation
        .form-group
          = f.label :name, "Picture", class: "col-lg-2 control-label"
          .col-lg-10
            = f.file_field :avatar, class: "form-control"
        .form-group
          = f.label :mision, "Reference Document", class: "col-lg-2 control-label"
          .col-lg-10
            = f.file_field :reference_document, class: "form-control", rows: "3"
        .form-group
          = f.label :vision, "Specification document", class: "control-label col-lg-2"
          .col-lg-10
            = f.file_field :specification_document, class: "form-control", rows: "2"
        .form-group
          = f.label :description, "Comments", class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :comments, class: "form-control", rows: "3"
        .form-group
          .col-lg-10.col-lg-offset-2
            = f.submit "Create project", class: "btn btn-primary"
            or go
            = link_to 'Back', projects_path, class: 'btn btn-default'

app/views/projects/_form_edit.html.haml
= form_for(@project, html: {class: "form-horizontal", multipart: true}) do |f|
  .col-lg-12
    .well
      %fieldset
        %legend Tech doc or description:
        .form-group
          = f.label :tecnical_document, class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :tecnical_document, class: "form-control", rows: "9", cols: "5"
        .form-group
          .col-lg-10.col-lg-offset-2
            = f.submit "Save changes", class: "btn btn-danger"
            or go
            = link_to 'Back', projects_path, class: 'btn btn-default'

  .col-lg-6
    .well
      - if @project.errors.any?
        .alert.alert-danger
          %h2
            = pluralize(@project.errors.count, "error")
            prohibited this project from being saved:
          %ul
            - @project.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        %legend Create a new project for manage
        .form-group
          = f.label :name, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_field :name, class: "form-control"
        .form-group
          = f.label :mision, class: "col-lg-2 control-label"
          .col-lg-10
            = f.text_area :mision, class: "form-control", rows: "3"
        .form-group
          = f.label :vision, class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :vision, class: "form-control", rows: "2"
        .form-group
          = f.label :description, class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :description, class: "form-control", rows: "3"
  .col-lg-6
    .well
      %fieldset
        %legend More documentation
        .form-group
          = f.label :description, "Comments", class: "control-label col-lg-2"
          .col-lg-10
            = f.text_area :comments, class: "form-control", rows: "3"

app/views/projects/edit.html.haml
%h1 Project details
= render 'form_edit'

app/views/projects/histories_current.html.haml
%p
.alert.alert-dismissable
  %button{type: "button", class: "close", "data-dismiss" => "alert" } ×

  .page-header
    %h2= @project.name

  - if notice
    .alert.alert-info
      %p#notice= notice

  .row
    .col-lg-6
      %p
        %strong Name:
        = @project.name
      %p
        %strong Mision:
        = @project.mision
      %p
        %strong Vision:
        = @project.vision
      %p
        %strong Description:
        = @project.description
      = link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning'
      |
      \#{link_to 'Back', projects_path, class: 'btn btn-primary' }
      |
      = link_to "Add new history", new_project_history_path(@project), class: 'btn btn-danger'
      |
      = link_to "See the table", project_path(@project), class: 'btn btn-info'
    .col-lg-2
      %p
        = link_to "See: specification document", @project.specification_document.url
      %p
        = link_to "See: reference document", @project.specification_document.url
    .col-lg-4
      = image_tag @project.avatar.url(:thumb)

      %p
      %p
  .row
    .col-lg-8
    .col-lg-4
      %input{type: "search", class: "form-control", placeholder: "Search on histories", id: "query_search_history"}

.page-header
  %b
    Histories in current
.row
  .col-lg-8
    - @project.histories_current.each do |history|
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            Name:
            = history.name
            .badge.badge-current
              = history.puntuation
        .panel-body
          %p
            %b Finished definition:
            = history.finished_definition
          %p
            %b Comments:
            = history.comments
          %hr
          = link_to "undo state", project_history_move_to_path(@project, history) + "?phase=pending", class: "btn btn-xs btn-warning"
          = link_to "move to finished", project_history_move_to_path(@project, history) + "?phase=finished", class: "btn btn-xs btn-default"
          = link_to "see details", project_history_path(@project, history), class: "btn btn-xs btn-info"

app/views/projects/index.html.haml
.page-header
  %h2 Listing projects

- if @projects.empty?
  .alert.alert-info
    Project list it's empty

.row
  .col-lg-8
    = link_to 'New Project', new_project_path, class: "btn btn-primary"
  .col-lg-4
    %input{type: "search", class: "form-control focusedInput", placeholder: "Search on projects: " }
%br
%br

- if !@projects.empty?
  %table.table
    %thead
      %tr
        %th Name
        %th Mision
        %th Vision
        %th Description
        %th
        %th
        %th
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          %td= project.mision
          %td= project.vision
          %td= project.description
          %td= link_to 'Show', project, class: 'btn btn-info'
          %td= link_to 'Edit', edit_project_path(project), class: 'btn btn-warning'
          %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/projects/new.html.haml
.page-header
  %h2 New project

= render 'form'

app/views/projects/show.html.haml
%p
.alert.alert-dismissable
  %button{type: "button", class: "close", "data-dismiss" => "alert" } ×
  .page-header
    %h2= @project.name

  %p#notice= notice
  %p
    %strong Name:
    = @project.name
  %p
    %strong Mision:
    = @project.mision
  %p
    %strong Vision:
    = @project.vision
  %p
    %strong Description:
    = @project.description
  = link_to 'Edit', edit_project_path(@project), class: 'btn btn-warning'
  |
  \#{link_to 'Back', projects_path, class: 'btn btn-primary' }
  |
  = link_to "Add new history", new_project_history_path(@project), class: 'btn btn-danger'
  |
  = link_to "See all the histories", project_histories_path(@project), class: 'btn btn-info'


.page-header
  %b
    Scrum Table

.row
  .col-lg-4
    %center
      %p
        %b Pending
    - @project.histories_pending.each do |history|
      .panel.panel-danger
        .panel-heading
          %h3.panel-title
            .badge.badge-pending
              = history.puntuation
            Nombre:
            = history.name
        .panel-body
          %p
            %b Finished definition:
            = history.finished_definition
          %p
            %b Comments:
            = history.comments
          %hr
          = link_to "current >>", project_history_move_to_path(@project, history) + "?phase=current", class: "btn btn-xs btn-default"
  .col-lg-4
    %center
      %p
        %b Current
    - @project.histories_current.each do |history|
      .panel.panel-info
        .panel-heading
          %h3.panel-title
            Nombre:
            = history.name
            |
            .badge.badge-current
              = history.puntuation
        .panel-body
          %p
            %b Finished definition:
            = history.finished_definition
          %p
            %b Comments:
            = history.comments
          %hr
          = link_to "finished >>", project_history_move_to_path(@project, history) + "?phase=finished", class: "btn btn-xs btn-default"
  .col-lg-4
    %center
      %p
        %b Finished
    - @project.histories_finished.each do |history|
      .panel.panel-success
        .panel-heading
          %h3.panel-title
            Nombre:
            = history.name
            |
            .badge.badge-finished
              = history.puntuation
        .panel-body
          %p
            %b Finished definition:
            = history.finished_definition
          %hr
          = link_to "hide >>", project_history_move_to_path(@project, history) + "?phase=hide", class: "btn btn-xs btn-default"